FROM node:9.5-alpine as builder
RUN apk add --update git python make g++ libnotify openssl
RUN npm install -g gulp-cli

WORKDIR /etherwallet
ADD . /etherwallet
RUN npm install
RUN npm run dist


FROM nginx

COPY --from=builder  /etherwallet/dist /usr/share/nginx/html

EXPOSE 80
